alter table public.products add column if not exists image_url text;
alter table public.order_items add column if not exists image_url text;
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/espresso.jpg' where name_en = 'Espresso';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/americano.jpg' where name_en = 'Americano';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/cortado.jpg' where name_en = 'Cortado';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/flatwhite.jpg' where name_en = 'Flat White';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/cappuccino.jpg' where name_en = 'Cappuccino';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/latte.jpg' where name_en = 'Latte';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/spanish-latte.jpg' where name_en = 'Spanish Latte';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/v60.jpg' where name_en = 'V60';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/iced-spanish-latte.jpg' where name_en = 'Iced Spanish Latte';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/iced-latte.jpg' where name_en = 'Iced Latte';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/iced-americano.jpg' where name_en = 'Iced Americano';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/cold-brew.jpg' where name_en = 'Cold Brew';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/espresso-tonic.jpg' where name_en = 'Espresso Tonic';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/mint-mojito.jpg' where name_en = 'Mint Mojito';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/lemon-mint.jpg' where name_en = 'Lemon Mint';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/strawberry-smoothie.jpg' where name_en = 'Strawberry Smoothie';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/peach-iced-tea.jpg' where name_en = 'Peach Iced Tea';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/passion-mojito.jpg' where name_en = 'Passion Mojito';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/matcha-latte.jpg' where name_en = 'Matcha Latte';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/iced-matcha.jpg' where name_en = 'Iced Matcha';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/karak.jpg' where name_en = 'Karak Tea';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/green-mint-tea.jpg' where name_en = 'Green Mint Tea';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/basque-cheesecake.jpg' where name_en = 'Basque Cheesecake';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/brownie.jpg' where name_en = 'Chocolate Brownie';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/cookie.jpg' where name_en = 'Choco Chip Cookie';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/kunafa-cream.jpg' where name_en = 'Kunafa Cream';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/ethiopia.jpg' where name_en = 'Ethiopia Yirgacheffe';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/colombia.jpg' where name_en = 'Colombia Huila';
update public.products set image_url = 'https://fygjdivdzrtviiommpoy.supabase.co/storage/v1/object/public/menu/brazil.jpg' where name_en = 'Brazil Cerrado';
