update public.products set base_price = 15000 where name_en = 'Espresso';
update public.products set base_price = 20000 where name_en = 'Americano';
update public.products set base_price = 22000 where name_en = 'Cortado';
update public.products set base_price = 28000 where name_en = 'Flat White';
update public.products set base_price = 30000 where name_en = 'Cappuccino';
update public.products set base_price = 30000 where name_en = 'Latte';
update public.products set base_price = 35000 where name_en = 'Spanish Latte';
update public.products set base_price = 40000 where name_en = 'V60';
update public.products set base_price = 38000 where name_en = 'Iced Spanish Latte';
update public.products set base_price = 32000 where name_en = 'Iced Latte';
update public.products set base_price = 25000 where name_en = 'Iced Americano';
update public.products set base_price = 35000 where name_en = 'Cold Brew';
update public.products set base_price = 45000 where name_en = 'Espresso Tonic';
update public.products set base_price = 30000 where name_en = 'Mint Mojito';
update public.products set base_price = 25000 where name_en = 'Lemon Mint';
update public.products set base_price = 40000 where name_en = 'Strawberry Smoothie';
update public.products set base_price = 28000 where name_en = 'Peach Iced Tea';
update public.products set base_price = 35000 where name_en = 'Passion Mojito';
update public.products set base_price = 42000 where name_en = 'Matcha Latte';
update public.products set base_price = 42000 where name_en = 'Iced Matcha';
update public.products set base_price = 18000 where name_en = 'Karak Tea';
update public.products set base_price = 15000 where name_en = 'Green Mint Tea';
update public.products set base_price = 55000 where name_en = 'Basque Cheesecake';
update public.products set base_price = 35000 where name_en = 'Chocolate Brownie';
update public.products set base_price = 22000 where name_en = 'Choco Chip Cookie';
update public.products set base_price = 45000 where name_en = 'Kunafa Cream';
update public.products set base_price = 150000 where name_en = 'Ethiopia Yirgacheffe';
update public.products set base_price = 135000 where name_en = 'Colombia Huila';
update public.products set base_price = 120000 where name_en = 'Brazil Cerrado';
